CREATE DATABASE IF NOT EXISTS userdb;
CREATE DATABASE IF NOT EXISTS bookdb;

CREATE USER IF NOT EXISTS 'Ahmed'@'%' IDENTIFIED BY 'Aa01117050928';
GRANT ALL PRIVILEGES ON userdb.* TO 'Ahmed'@'%';
GRANT ALL PRIVILEGES ON bookdb.* TO 'Ahmed'@'%';
FLUSH PRIVILEGES;