spring.application.name=book-service

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
server.port=${SERVER_PORT}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}

spring.jpa.hibernate.ddl-auto=${HIBERNATE_DDL_AUTO}
spring.jpa.properties.hibernate.id.new_generator_mappings=${HIBERNATE_ID_MAPPINGS}
spring.jpa.properties.hibernate.type.preferred_uuid_jdbc_type=${UUID_STORAGE_TYPE}