spring.application.name=eureka-server

server.port=${SERVER_PORT:8761}

eureka.instance.prefer-ip-address=${EUREKA_PREFER_IP:true}
eureka.client.register-with-eureka=${EUREKA_REGISTER_WITH:false}
eureka.client.fetch-registry=${EUREKA_FETCH_REGISTRY:false}
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka}

spring.jpa.properties.hibernate.type.preferred_uuid_jdbc_type=${UUID_STORAGE_TYPE:VARCHAR}
